

version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./keys:/etc/nginx/keys:ro
      - ./cert:/etc/nginx/cert:ro
      - ./webserver/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./webserver/nginx-server.conf:/etc/nginx/server:ro
    depends_on:
      - php
    restart: always
    ports:
      - 443:443
      - 80:80
    networks:
      - tangled-network
  php:
    image: php:8.0-fpm
    container_name: php8_fpm
    volumes:
      - ./php:/var/www/html
      - ./php8-fpm/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
    restart: always
    networks:
      - tangled-network

networks:
  tangled-network:
    driver: bridge


volumes:
  html:
  keys:
