

version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: tangled-nginx
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./keys:/etc/nginx/keys:ro
      - ./cert:/etc/nginx/cert:ro
      - ./webserver/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./webserver/nginx-server.conf:/etc/nginx/server:ro
    depends_on:
      - php
    restart: always
    #ports:
    #  - 8443
    #  - 8000
    network_mode: "host"

  php:
    container_name: tangled1-php8_fpm
    #image: php:8.0-fpm
    build: 
      context: ./php8-fpm/
      #dockerfile: ../Dockerfile
    volumes:
      - ./php:/var/www/html
      - ./php8-fpm/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
    restart: always
    #ports:
    #  - 9000
    network_mode: "host"

volumes:
  html:
  keys:
